name: BuildAndDeploy
run-name: ${{github.actor}} is building and deploying.
on:
  push:
    branches:
      - 'main'
  workflow_dispatch:
jobs:
  News:
    name: News
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Test
        run : make check
      - name: Codecov
        uses: codecov/codecov-action@v3
        with:
          files: ./tmp/coverage.xml
          token: ${{ secrets.CODECOV_TOKEN }}
